plugins {
    id 'java'
    id 'java-library'
    alias libs.plugins.radar.root.project
}

radarRootProject {
    projectVersion = libs.versions.project
    gradleVersion = libs.versions.gradle
}

description = "Kafka Connect transformation used to copy the key and value to a struct in the value of the record."

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
}

dependencies {
    compileOnly libs.kafka.connect.transforms
}
